### PR TITLE
i18next-client as dependency

### PR DESCRIPTION
**Pull request by lennym**
As discussed in https://github.com/i18next/i18next-node/pull/183 - load files in ./lib/dep from i18next-client package instead of keeping local copies in this repo.

### CODE REVIEW

**Comment by mathieumg** [comment]
@jamuhl I'd be really interested in having this, do you have a release planned soon? I'm still affected by the bug described in https://github.com/i18next/i18next/issues/341 since this repo wasn't updated since to account for the fix in the client.

**Comment by jamuhl** [comment]
@mathieumg if time allows it i planned to release updates next week. hope that's soon enough...this week i don't get to it.

**Comment by mathieumg** [comment]
No problem, that's suitable! Thank you.

**Comment by mathieumg** [comment]
I don't mean to be impatient but I see you just published a new version of the client and the server version hasn't had a new publish in over 3 months now. Is there anything that prevents you from publishing with which I could help? Thank you!

**Comment by jamuhl** [comment]
sorry noo...don't get me wrong...i somewhere else told i will update client and server by this week.

i just published client today as server depends on it. expect the server update to come this week too.

**Comment by mathieumg** [comment]
Alright, thanks for the update, good work!

**Comment by jamuhl** [comment]
v1.9.0 is published...sorry for the delay

**Comment by mathieumg** [comment]
:tada: Yay! Thanks! :grinning:

**Pull request merged**
